### ISSUE TITLE
Turn on github pages?

### ISSUE THREAD

**Issue by courajs** [bvschwartz/nock-step#1]
Rawgit has shut down, breaking demo links in the readme.

Github pages support is pretty good now though - Don't even need to make a `gh-pages` branch or anything. Just go into settings, and mark `master` as the source for pages, and https://bvschwartz.github.io/nock-step will work.

I'll even PR link fixes to the readme if you enable it!

**Comment by bvschwartz** [comment]
Fixed!  But there is still a link to the old nock reference which used to be at https://github.com/urbit/urbit/blob/master/urb/zod/pub/doc/nock/reference.md.

I don't know where it is now or if it even exists anymore...

**Comment by courajs** [comment]
Thanks!

Closest is probably https://urbit.org/docs/learn/arvo/nock/definition/ or https://urbit.org/docs/learn/arvo/nock/explanation/

Not sure either of those are the same though.
